version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.9

    working_directory: /go/src/github.com/pubnative/consent
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: go test -v ./...
